repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: (^docs/)

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 1.0.1
    hooks:
      - id: flakeheaven
        entry: flakeheaven lint
